# Generated by Django 5.1.3 on 2024-12-13 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myvieal", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="like",
            field=models.ManyToManyField(related_name="movie_like", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="movie",
            name="spot",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField()),
                ("commented_at", models.DateTimeField(auto_now_add=True)),
                (
                    "commented_by",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
                ("commented_on", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="myvieal.movie")),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("animals", "動物"),
                            ("food", "食べ物"),
                            ("locations", "場所"),
                            ("anime", "アニメ"),
                            ("movies", "映画"),
                            ("gaming", "ゲーム"),
                            ("electronic_equipment", "電子機器"),
                            ("sports", "スポーツ"),
                            ("music", "音楽"),
                            ("art", "アート"),
                            ("culture", "文化"),
                            ("science", "科学"),
                            ("history", "歴史"),
                            ("literature", "文学"),
                            ("fashion", "ファッション"),
                            ("person", "人物"),
                            ("health", "健康"),
                            ("education", "教育"),
                            ("business", "ビジネス"),
                            ("politics", "政治"),
                            ("social_issues", "社会問題"),
                            ("nature", "自然"),
                            ("events", "イベント"),
                            ("feeling", "感覚"),
                            ("misc", "その他"),
                        ],
                        max_length=128,
                    ),
                ),
                ("number", models.IntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.AddField(
            model_name="movie",
            name="tag_list",
            field=models.ManyToManyField(related_name="movie", to="myvieal.tag"),
        ),
    ]
