# Generated by Django 5.1.3 on 2024-12-18 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myvieal', '0002_movie_like_movie_spot_comment_tag_movie_tag_list'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='address',
            field=models.CharField(max_length=255, null=True, verbose_name='住所'),
        ),
        migrations.AddField(
            model_name='movie',
            name='place_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='spot',
            field=models.CharField(default='Untitled', max_length=255, verbose_name='施設名'),
        ),
        migrations.CreateModel(
            name='MapHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='住所')),
                ('name', models.CharField(max_length=255)),
                ('place_id', models.CharField(max_length=255, null=True)),
                ('map_searched_at', models.DateTimeField(auto_now_add=True)),
                ('map_searched_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
