# Generated by Django 5.1.3 on 2024-11-22 12:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myvieal", "0002_alter_follow_from_user_alter_follow_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="follow",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="follow",
            name="from_user",
        ),
        migrations.RemoveField(
            model_name="follow",
            name="to_user",
        ),
    ]
