# Generated by Django 5.1.3 on 2024-11-22 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myvieal', '0003_alter_follow_from_user_alter_follow_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
