# Generated by Django 5.1.3 on 2024-11-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myvieal', '0003_alter_follow_from_user_alter_follow_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='サムネ'),
        ),
    ]
