# Generated by Django 5.1.3 on 2024-11-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myvieal', '0004_movie_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='number_of_views',
            field=models.IntegerField(default=0),
        ),
    ]
