# Generated by Django 5.1.3 on 2024-11-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myvieal", "0004_delete_follow"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="images/", verbose_name="さむね"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="number_of_views",
            field=models.IntegerField(default=0),
        ),
    ]
