# Generated by Django 5.1.3 on 2025-01-10 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myvieal", "0004_rename_spot_movie_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="myvieal.comment"),
        ),
    ]
