# Generated by Django 5.1.3 on 2024-12-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='terms_of_service_version',
            field=models.IntegerField(default=0),
        ),
    ]
