# Generated by Django 5.1.3 on 2024-11-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="icon_image",
            field=models.ImageField(null=True, upload_to="user"),
        ),
    ]
