# Generated by Django 5.1.3 on 2024-11-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="icon_image",
            field=models.ImageField(
                default="myvieal/img/icon_KiGiEsSyQLlycwpDjVYUn0jCqGWzHURP4iJQwrFVLGM=.png",
                null=True,
                upload_to="user/",
            ),
        ),
    ]
