# Generated by Django 5.1.3 on 2024-11-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_customuser_icon_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="icon_image",
            field=models.ImageField(null=True, upload_to="user/"),
        ),
    ]
