# Generated by Django 5.1.3 on 2024-11-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_customuser_icon_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="icon_image",
            field=models.ImageField(default="misc/722e64ef8f12418691bf75c04b83ebbe.png", null=True, upload_to="user/"),
        ),
    ]
